### PR TITLE
Change build.sh and CMakeLists.txt to support pinned test on  CentOS 8/7, Ubuntu 16/18/20, Amazon Linux 2, MacOS 10.15

### PR DESCRIPTION
**Pull request by softprofe**
## Change Description

Start 511 description ......
In this pull, I solve the link errors which happened on pinned build,  per my test, It works on CentOS8, CentOS7, Ubuntu 16, Ubuntu 18, Ubuntu20, Amazon Linux 2, MacOs 10.15 .  The eosio.contracts/tests has problem of tool chain mismatch with eos so the error happen. The way to solve it is to set a falg  in build.sh to let CMakeLists.txt know currently is building pinned tests, so include the pinned tool chain file.  

This pull won't change anything if not pinned build.   

Currently Don't support  install directory of eos like $HOME/eosio/2.1,  only support build directory something like  $HOME/work/eos/build, the reason is pinned_toolchain.cmake can't be found under $HOME/eosio/2.1;  it doesn't sound perfect but at least this pull can build tests without a lot of link errors.

Please note that per my test this pull solve but only solve link error caused by tool chain mismatch with eos, if other problem such as some package can't found by cmake, some CMAKE flag is missing, that is not related to this pull.  if some error happen before run import pinned_toolchain.cmake or after that but no any relation with it, just solve them other where, this pull only solve one problem and I test it on upper platform it works.  

End 511 description...

## Change Type
**Select ONE**
- [ ] Documentation

- [ ] Stability bug fix

- [x] Other

- [ ] Other - special case

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Comment by spoonincode** [comment]
Why limit such a change to centos? Why not support pinned compilers no matter the platform?

**Comment by softprofe** [comment]
> Why limit such a change to centos? Why not support pinned compilers no matter the platform?

Other platform not yet tested, I'm sure it work or not. As my EPE  is supporting Centos 8, and Jingjun said his passed build using my way, So, Centos 8 and 7 take as tested.

**Comment by softprofe** [comment]
> > Why limit such a change to centos? Why not support pinned compilers no matter the platform?
> 
> Other platform not yet tested, I'm sure it work or not. As my EPE is supporting Centos 8, and Jingjun said his passed build using my way, So, Centos 8 and 7  can be taken as tested.

**Comment by spoonincode** [comment]
Any idea what the unit test failures are about? Due to this change or were the failures preexisting?

**Review by jeffreyssmith2nd — APPROVED** [review]

**Pull request merged**
