### PR TITLE
Remove artificial REX lower limit

### PR DESCRIPTION
**Pull request by jafri**
Removes REX lower unlent limit from 20% to 0%

### CODE REVIEW

**Comment by sergioyuhjtman** [comment]
Have you considered what would happen if total_unlent becomes small? Apparently the rental fee might fall drastically for subsequent loans.
In the case where total_unlent equals 0 the rental fee becomes 0 after the expiration of a loan.
See https://medium.com/eosio/analysis-of-bancor-equations-supporting-rex-74ef4aaeca1c (sections "Loan Expiration" and "Unlent Balance Lower Bound").

**Comment by jafri** [comment]
@sergioyuhjtman When a loan expires, the rented resources are moved from `total_lent` to `total_unlent`, so it could not be 0. Even if the user has `auto_renew` enabled, `remove_loan_from_rex_pool` would move `total_lent`->`total_unlent` first.

The amount of CPU one gets per EOS is determined by `total_unlent / (total_rent + 1)`. As `total_unlent` goes down, you get less and less CPU for every EOS.

e.g. if total_unlent was 10,000 EOS and total_rent was 99,990,000 EOS, you would get 0.0001 EOS of CPU

**Comment by andybets** [comment]
@jafri it does seem that if there are loans outstanding and rex holders pull out all the unlent rex, `total_unlent` can go to zero, and thus `total_rent` is set to 0 (at loan expiration). When that happens, REX is unstable and a future rental paying 1 EOS would get the full unlent amount.

So there is a reason for the buffer. We need to set it above zero.

**Comment by jafri** [comment]
@andybets how can a future rental paying 1 EOS get the full unlent amount, when the premise of that is `total_unlent` going to 0 by r ex holders pulling it all out

**Comment by jafri** [comment]
Fair enough @andybets

That edge case would only apply to the first loan after it hits 0

The minimum unlent lower bound value can be set to 1 instead of 0

**Comment by andybets** [comment]
I'm trying to establish what happens to `total_rent` where unlent is low but non-zero. I suspect there's a reason they set it to 20% rather than 1%. Can't quite follow the maths yet though... more coffee needed.

**Comment by gleehokie** [comment]
The root issue has been addressed by https://github.com/EOSIO/eosio.contracts/pull/381.

**Pull request closed without merging**
